"""Initial migration

Revision ID: 0d1aedc7a826
Revises: 
Create Date: 2025-01-07 16:42:01.572313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1aedc7a826'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('tracking_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'packages', ['tracking_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'packages', type_='unique')
    op.drop_column('packages', 'tracking_number')
    # ### end Alembic commands ###
