"""Initial migration

Revision ID: 1a1a328a0387
Revises: 
Create Date: 2025-02-25 21:12:34.074280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1a328a0387'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_couriers_email'), 'couriers', ['email'], unique=True)
    op.create_index(op.f('ix_couriers_uuid'), 'couriers', ['uuid'], unique=True)
    op.create_table('packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('package_type', sa.Enum('electronics', 'clothing', 'food', 'books', 'furniture', 'cosmetics', 'documents', 'jewelry', 'tools', 'toys', 'pharmaceuticals', 'household_items', 'sports_equipment', 'artwork', 'musical_instruments', 'automotive_parts', 'perishables', 'beverages', 'industrial_supplies', 'pet_supplies', 'gardening_supplies', 'others', name='packagetype'), nullable=False),
    sa.Column('origin_state', sa.String(), nullable=False),
    sa.Column('origin_city', sa.String(), nullable=False),
    sa.Column('destination_state', sa.String(), nullable=False),
    sa.Column('destination_city', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('courier_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_number')
    )
    op.create_index(op.f('ix_packages_package_type'), 'packages', ['package_type'], unique=False)
    op.create_index(op.f('ix_packages_uuid'), 'packages', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packages_uuid'), table_name='packages')
    op.drop_index(op.f('ix_packages_package_type'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_couriers_uuid'), table_name='couriers')
    op.drop_index(op.f('ix_couriers_email'), table_name='couriers')
    op.drop_table('couriers')
    # ### end Alembic commands ###
